version: '2'
services:
    smartvienna-app:
        image: smartvienna
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://smartvienna-postgresql:5432/smartVienna
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    smartvienna-postgresql:
        extends:
            file: postgresql.yml
            service: smartvienna-postgresql
